### ISSUE TITLE
Timer threads are not yet working

### ISSUE THREAD

**Issue by jorndorff** [pingryiRT/P2P-Platform#3]
It seems that the scheduling with Threading.Timer isn't working.

It seems like the threads are never started because my test print function on line 98 never prints anything.

And yet shutdown always leaves the terminal hanging as if there are daemon threads still running. Actually this happens even when autoPoll is never set.

**Comment by mpavlak2018** [comment]
This probably isn't the answer, but one thing I did notice is that I believe both timers call the same autoacceptor (I believe the intention is probably to have one on acceptor and one on receiver)

**Comment by jorndorff** [comment]
Good catch. I fixed that in the latest commit, although I had forgotten to push it until just now. You're right that it wasn't the only problem.

**Comment by mpavlak2018** [comment]
Did you try moving the print up to the top of the acceptor function or having a peer connect to the network? I thought that the accept() call was blocking...

**Comment by jorndorff** [comment]
Ohhhh, I just realized what call you were talking about earlier, and you're absolutely right that I had one wrong. Fixing it fixed the problem. And you're also right that accept is blocking which is why acceptor wasn't getting rescheduled. Great debugging. I'll push the latest work right meow.
