### ISSUE TITLE
Network should inform peers when shutting down

### ISSUE THREAD

**Issue by jorndorff** [pingryiRT/P2P-Platform#8]
So that they can disconnect appropriately.

This should probably happen in `Network.shutdown`

**Comment by mpavlak2018** [comment]
This is actually currently built in, but very messily (it was part of how I did it when it was all combined, with the new architecture it doesn't really look neat at all—should change this eventually)--> Basically, when I want to shutdown, I type /exit, and in addition to breaking the loop, before breaking /exit is actually sent to all of my peers... when a peer receives a /exit message they know that peer is shutting down. Agree that it should definitely be changed, and is probably something we'll want to do right after the proposal

**Comment by jorndorff** [comment]
This is now implemented using the formal xml schema as of b3e5c71dacd9e047f0b32329209ac7773241b41d
